"""Schema model init

Revision ID: 09a62e3cfb52
Revises: 
Create Date: 2026-09-07 09:33:16.229395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a62e3cfb52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('unique_constraint'), table_name='URL_Stats_table')
    op.drop_index(op.f('uq'), table_name='URL_Stats_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq'), 'URL_Stats_table', ['url_id', 'date'], unique=True)
    op.create_index(op.f('unique_constraint'), 'URL_Stats_table', ['url_id', 'date'], unique=True)
    # ### end Alembic commands ###
