"""Unique enable for short link

Revision ID: 09cc35dc8dff
Revises: 2ada7a08929c
Create Date: 2026-09-09 10:14:12.157462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cc35dc8dff'
down_revision: Union[str, Sequence[str], None] = '2ada7a08929c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'URL_table', ['short_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'URL_table', type_='unique')
    # ### end Alembic commands ###
