"""URL Stats table delete and Delete relationship of it

Revision ID: 2da20a21ce10
Revises: db49f8ebd85e
Create Date: 2026-09-15 09:52:21.426177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2da20a21ce10'
down_revision: Union[str, Sequence[str], None] = 'db49f8ebd85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('uq_URLStats_url_date'), table_name='URL_Stats_table')
    op.drop_table('URL_Stats_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL_Stats_table',
    sa.Column('stats_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('clicks_per_day', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['URL_table.url_id'], name=op.f('URL_Stats_table_ibfk_1')),
    sa.PrimaryKeyConstraint('stats_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_URLStats_url_date'), 'URL_Stats_table', ['url_id', 'date'], unique=True)
    # ### end Alembic commands ###
