"""Schema with unique constraint

Revision ID: 3daa6949fff2
Revises: 
Create Date: 2026-09-09 09:43:48.157011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3daa6949fff2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('uq'), table_name='URL_Stats_table')
    op.create_unique_constraint('uq_URLStats_url_date', 'URL_Stats_table', ['url_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_URLStats_url_date', 'URL_Stats_table', type_='unique')
    # op.create_index(op.f('uq'), 'URL_Stats_table', ['url_id', 'date'], unique=True)
    # ### end Alembic commands ###
