"""Stats table fix using clean and alter data using unique constraint

Revision ID: 791686afda01
Revises: eaaac0d3086b
Create Date: 2026-08-31 12:39:30.702129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '791686afda01'
down_revision: Union[str, Sequence[str], None] = 'eaaac0d3086b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_url_date'), table_name='URL_Stats_table')
    op.drop_column('URL_table', 'secret_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL_table', sa.Column('secret_key', mysql.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('uq_url_date'), 'URL_Stats_table', ['url_id', 'date'], unique=True)
    # ### end Alembic commands ###
