"""Add IP , remove unique -> Referer attr 

Revision ID: 9ff3ba70f6bb
Revises: 8c154405266c
Create Date: 2026-09-29 11:40:46.942972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff3ba70f6bb'
down_revision: Union[str, Sequence[str], None] = '8c154405266c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClickLog_table', sa.Column('ip', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClickLog_table', 'ip')
    # ### end Alembic commands ###
