"""initialization

Revision ID: a842455e6848
Revises: 
Create Date: 2026-08-31 09:28:24.763795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a842455e6848'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('URL_Stats_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL_Stats_table',
    sa.Column('total_clicks', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clicks_per_day', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['URL_table.url_id'], name=op.f('URL_Stats_table_ibfk_1')),
    sa.PrimaryKeyConstraint('url_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
