"""IP init in clicklog

Revision ID: b862f64f3601
Revises: 
Create Date: 2026-09-08 11:04:01.302101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b862f64f3601'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClickLog_table', sa.Column('ip', sa.String(length=255), nullable=False))
    op.drop_index(op.f('uq'), table_name='URL_Stats_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq'), 'URL_Stats_table', ['url_id', 'date'], unique=True)
    op.drop_column('ClickLog_table', 'ip')
    # ### end Alembic commands ###
