"""Log and Analytics Table

Revision ID: eaaac0d3086b
Revises: a842455e6848
Create Date: 2026-08-31 10:52:06.089738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eaaac0d3086b'
down_revision: Union[str, Sequence[str], None] = 'a842455e6848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClickLog_table', sa.Column('url_id', sa.Integer(), nullable=False))
    op.add_column('ClickLog_table', sa.Column('clicked_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'ClickLog_table', 'URL_table', ['url_id'], ['url_id'])
    op.drop_column('URL_table', 'secret_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL_table', sa.Column('secret_key', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'ClickLog_table', type_='foreignkey')
    op.drop_column('ClickLog_table', 'clicked_at')
    op.drop_column('ClickLog_table', 'url_id')
    # ### end Alembic commands ###
